<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/user/entity.proto

namespace User\V1\GPBMetadata;

class Entity
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xF5\x01\x0A\x18protos/user/entity.proto\x12\x07user.v1\"@\x0A\x04User\x12\x0E\x0A\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\x0A\x05email\x18\x02 \x01(\x09R\x05email\x12\x12\x0A\x04name\x18\x03 \x01(\x09R\x04nameB\x85\x01\x0A\x0Bcom.user.v1B\x0BEntityProtoP\x01Z,github.com/twaydev/libs/proto/user/v1;userv1\xA2\x02\x03UXX\xAA\x02\x07User.V1\xCA\x02\x07User\\V1\xE2\x02\x13User\\V1\\GPBMetadata\xEA\x02\x08User::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

