FROM node:25-alpine AS builder
RUN npm install -g pnpm
WORKDIR /app
COPY frontend/ .
RUN CI=true pnpm install
RUN pnpm --filter web build

FROM node:25-alpine
WORKDIR /app
COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder /app/apps/web/public ./apps/web/public
ENV NODE_ENV=production
ENV PORT=80
EXPOSE 80
CMD ["node", "apps/web/server.js"]
